# Use an official Python runtime as the base image
FROM python:3.12

# Set the working directory inside the container
WORKDIR /app

# Copy your application code into the container
COPY . /app 

# Specify the command to run your app
CMD ["python3", "task2.py"]  
